name: 'Delete stale branches'
description: 'Notify authors of old branches and auto delete if no action is taken'
outputs:
  deleted-branches:
    description: "List of all deleted branches"
    value: ${{ steps.deleted-branches.outputs.deleted-branches }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.8' 
    - name: Install Python and Run Script
      working-directory: "${{ github.action_path }}"
      shell: bash
      run: |
        pip install pipenv
        pipenv install Pipfile
    - name: Triage branches
      working-directory: "${{ github.action_path }}"
      run: |
        output=$(pipenv run python3 src/purge_branches.py)
        echo "::set-output name=deleted-branches::$output"
      id: deleted-branches
      shell: bash
    - name: Print deleted branches
      run: echo "Print deleted branches -- ${{ steps.deleted-branches.outputs.deleted-branches }}"
      shell: bash